GPUS: (0,)
WORKERS: 15
PRINT_FREQ: 50
IMAGE_RESIZE:
  - 800
  - 800
MODEL:
  NAME: 'hrnet'
  NUM_JOINTS: 1
  INIT_WEIGHTS: true
  PRETRAINED: './models/pretrained/hrnetv2_w18_imagenet_pretrained.pth'
  SIGMA: 1.5
  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
      NUM_CHANNELS:
        - 18
        - 36
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 18
        - 36
        - 72
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 18
        - 36
        - 72
        - 144
      FUSE_METHOD: SUM
TRAIN:
  BATCH_SIZE_PER_GPU: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 500
  EARLY_STOP: 30
  OPTIMIZER: 'adam'
  LR: 0.0001
  WD: 0.0
  LR_STEP: [25, 40]
  MOMENTUM: 0.0
  NESTEROV: false
TEST:
  BATCH_SIZE_PER_GPU: 8